version: "3.8"

services:

  boot-otel-tempo-provider1:
    image: "mnadeem/boot-otel-tempo-provider1:0.0.1-SNAPSHOT"
    ports:
      - "8090:8090"
    environment:
      PROVIDER1_DB_URL: jdbc:postgresql://provider1-db:5432/reconeyez
      PROVIDER1_DB_USER: postgres
      PROVIDER1_DB_PASS: root
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - provider1-db

  provider1-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=reconeyez
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./reconeyez/db/data:/var/lib/postgresql
      - ./reconeyez/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql